const SIEF={users:'sief_users',orders:'sief_orders',session:'sief_session',theme:'sief_theme'};
const get=(k,d=[])=>JSON.parse(localStorage.getItem(k)||JSON.stringify(d));
const set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const statusClass=s=>s.replaceAll(' ','-');
function seed(){if(!localStorage.getItem(SIEF.users))set(SIEF.users,[{id:'admin-1',name:'Administrador SIEF',email:'admin@sief.com',password:'Sief@2026',role:'admin'}]);if(!localStorage.getItem(SIEF.orders))set(SIEF.orders,[])}seed();
function current(){return get(SIEF.session,null)}
function requireLogin(admin=false){const u=current();if(!u||(admin&&u.role!=='admin')){location.href='login.html';return null}return u}
function logout(){localStorage.removeItem(SIEF.session);location.href='index.html'}
function card(label,value){return `<article class="stat"><small>${label}</small><strong>${value}</strong></article>`}
function ordersFor(u){return get(SIEF.orders).filter(o=>o.userId===u.id)}
function calc(type,kg,km){return(Number(km)*2+Number(kg)*.35+35)*({'Nao Perecivel':1,'Perecivel':1.18,'Congelado':1.55,'Graos':.9}[type]||1)}
function applyTheme(){document.body.dataset.theme=localStorage.getItem(SIEF.theme)||'light'}
function updateSessionUser(u){set(SIEF.session,u)}
function initAuth(){const login=document.querySelector('#loginForm'),register=document.querySelector('#registerForm');if(login)login.onsubmit=e=>{e.preventDefault();const emailInput=document.querySelector('#email'),passwordInput=document.querySelector('#senha'),feedback=document.querySelector('#loginFeedback');const user=get(SIEF.users).find(x=>x.email.toLowerCase()===emailInput.value.trim().toLowerCase()&&x.password===passwordInput.value);if(!user){feedback.textContent='E-mail ou senha invalidos.';return}set(SIEF.session,user);location.href=user.role==='admin'?'admin.html':'cliente.html'};if(register)register.onsubmit=e=>{e.preventDefault();const name=document.querySelector('#nome'),emailInput=document.querySelector('#cadEmail'),password=document.querySelector('#cadSenha'),confirmPassword=document.querySelector('#confirmarSenha'),feedback=document.querySelector('#registerFeedback'),users=get(SIEF.users),email=emailInput.value.trim().toLowerCase();if(password.value!==confirmPassword.value){feedback.textContent='As senhas nao coincidem.';return}if(users.some(x=>x.email.toLowerCase()===email)){feedback.textContent='Este e-mail ja esta cadastrado.';return}const user={id:crypto.randomUUID(),name:name.value.trim(),email,password:password.value,role:'client'};users.push(user);set(SIEF.users,users);set(SIEF.session,user);location.href='cliente.html'}}
function initProfile(){const form=document.querySelector('#profileForm');if(!form)return;const u=requireLogin();if(!u)return;const isAdmin=u.role==='admin';profileHome.href=isAdmin?'admin.html':'cliente.html';profileMenu.innerHTML=isAdmin?'<a href="admin.html">Dashboard</a><a href="clientes.html">Clientes</a><a class="active" href="perfil.html">Perfil</a>':'<a href="cliente.html">Minha area</a><a class="active" href="perfil.html">Perfil</a>';document.querySelector('#profileName').value=u.name;document.querySelector('#profileEmail').value=u.email;document.querySelector('#themeChoice').value=localStorage.getItem(SIEF.theme)||'light';form.onsubmit=e=>{e.preventDefault();const users=get(SIEF.users);const duplicate=users.some(x=>x.email===profileEmail.value.trim().toLowerCase()&&x.id!==u.id);if(duplicate){profileFeedback.textContent='Este e-mail ja esta em uso.';return}const updated={...u,name:profileName.value.trim(),email:profileEmail.value.trim().toLowerCase()};const i=users.findIndex(x=>x.id===u.id);users[i]=updated;set(SIEF.users,users);updateSessionUser(updated);localStorage.setItem(SIEF.theme,themeChoice.value);applyTheme();profileFeedback.textContent='Perfil atualizado com sucesso.';profileFeedback.className='feedback success';document.querySelectorAll('#userName').forEach(x=>x.textContent=updated.name)}}
function initClient(){const u=requireLogin();if(!u)return;const originInput=document.querySelector('#origin');userName.textContent=u.name;clientName.textContent=u.name;const render=()=>{const os=ordersFor(u);clientStats.innerHTML=card('Pedidos cadastrados',os.length)+card('Em andamento',os.filter(o=>o.status!=='Chegou ao Destino').length)+card('Total em fretes',money(os.reduce((a,o)=>a+o.price,0)));trackingList.innerHTML=os.length?os.slice().reverse().map(o=>`<article class="tracking-card"><div><h3>${o.id.slice(0,8).toUpperCase()} - ${o.type}</h3><p><b>${o.origin}</b> &rarr; <b>${o.destination}</b> - ${o.quantity} kg</p><p class="muted">Frete: ${money(o.price)} - ${o.date}</p></div><span class="status ${statusClass(o.status)}">${o.status}</span><div class="card-actions"><button class="text-button edit" data-id="${o.id}">Editar</button><button class="text-button danger delete" data-id="${o.id}">Excluir</button></div></article>`).join(''):'<p class="muted">Voce ainda nao cadastrou pedidos.</p>'};render();
openOrder.onclick=()=>{orderForm.reset();orderId.value='';freightValue.textContent='R$ 0,00';orderModalTitle.textContent='Novo pedido';orderModal.showModal()};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>orderModal.close());['foodType','quantity','distance'].forEach(id=>document.querySelector('#'+id).oninput=()=>freightValue.textContent=money(calc(foodType.value,quantity.value,distance.value)));orderForm.onsubmit=e=>{e.preventDefault();const orders=get(SIEF.orders),id=orderId.value,data={id:id||crypto.randomUUID(),userId:u.id,type:foodType.value,quantity:+quantity.value,origin:originInput.value.trim(),destination:destination.value.trim(),distance:+distance.value,price:calc(foodType.value,quantity.value,distance.value),status:'Preparando',date:new Date().toLocaleDateString('pt-BR')},i=orders.findIndex(o=>o.id===id);if(i>=0){data.status=orders[i].status;orders[i]=data}else orders.push(data);set(SIEF.orders,orders);orderModal.close();render()};trackingList.onclick=e=>{const id=e.target.dataset.id;if(e.target.classList.contains('delete')&&confirm('Excluir este pedido?')){set(SIEF.orders,get(SIEF.orders).filter(o=>o.id!==id));render()}if(e.target.classList.contains('edit')){const o=get(SIEF.orders).find(x=>x.id===id);orderId.value=o.id;foodType.value=o.type;quantity.value=o.quantity;originInput.value=o.origin;destination.value=o.destination;distance.value=o.distance;freightValue.textContent=money(o.price);orderModalTitle.textContent='Editar pedido';orderModal.showModal()}}}
function initReports(){const u=requireLogin();if(!u)return;userName.textContent=u.name;const os=ordersFor(u);reportStats.innerHTML=card('Pedidos',os.length)+card('Entregues',os.filter(o=>o.status==='Chegou ao Destino').length)+card('Total contratado',money(os.reduce((a,o)=>a+o.price,0)));reportTable.innerHTML=os.slice().reverse().map(o=>`<tr><td>${o.id.slice(0,8).toUpperCase()}</td><td>${o.type}<br><small>${o.quantity} kg</small></td><td>${o.origin} &rarr; ${o.destination}</td><td>${money(o.price)}</td><td><span class="status ${statusClass(o.status)}">${o.status}</span></td><td>${o.date}</td></tr>`).join('')||'<tr><td colspan="6">Nenhum pedido cadastrado.</td></tr>'}
function initAdmin(){const u=requireLogin(true);if(!u)return;userName.textContent=u.name;const render=()=>{const os=get(SIEF.orders),clients=get(SIEF.users).filter(x=>x.role==='client');adminStats.innerHTML=card('Clientes cadastrados',clients.length)+card('Pedidos totais',os.length)+card('Receita estimada',money(os.reduce((a,o)=>a+o.price,0)));adminTable.innerHTML=os.length?os.slice().reverse().map(o=>{const c=clients.find(x=>x.id===o.userId);return `<tr><td><b>${o.id.slice(0,8).toUpperCase()}</b><br><small>${c?.name||'Cliente removido'}</small></td><td>${o.type}<br><small>${o.quantity} kg</small></td><td>${o.origin} &rarr; ${o.destination}<br><small>${o.distance} km</small></td><td>${money(o.price)}</td><td><select data-status="${o.id}">${['Preparando','A Caminho','Chegou ao Destino'].map(s=>`<option ${o.status===s?'selected':''}>${s}</option>`).join('')}</select></td><td><button class="button update" data-id="${o.id}">Atualizar</button></td></tr>`}).join(''):'<tr><td colspan="6">Ainda nao ha pedidos.</td></tr>'};render();adminTable.onclick=e=>{if(!e.target.classList.contains('update'))return;const id=e.target.dataset.id,os=get(SIEF.orders),o=os.find(x=>x.id===id),client=get(SIEF.users).find(x=>x.id===o.userId);o.status=document.querySelector(`[data-status="${id}"]`).value;set(SIEF.orders,os);render();adminFeedback.textContent=`Status do ${client?.name||'cliente'} atualizado com sucesso.`;adminFeedback.hidden=false}}
function initClients(){const u=requireLogin(true);if(!u)return;userName.textContent=u.name;const clients=get(SIEF.users).filter(x=>x.role==='client');clientDataTable.innerHTML=clients.length?clients.map(c=>`<tr><td>${c.name}</td><td>${c.email}</td><td>${ordersFor(c).length}</td></tr>`).join(''):'<tr><td colspan="3">Ainda nao ha clientes cadastrados.</td></tr>'}
function initAccess(){document.querySelectorAll('[data-logout]').forEach(x=>x.onclick=logout);const side=document.querySelector('aside');let toggle=document.querySelector('#menuToggle');if(!toggle&&side){toggle=document.createElement('button');toggle.id='menuToggle';toggle.setAttribute('aria-label','Mostrar ou esconder menu')}document.querySelector('#librasBtn')?.remove();if(toggle&&side){toggle.textContent='☰';toggle.classList.add('menu-toggle','side-menu-toggle');side.prepend(toggle);toggle.onclick=()=>document.querySelector('.app-layout').classList.toggle('menu-hidden')}const tb=document.querySelector('#tutorialBtn'),t=document.querySelector('#tutorial');if(tb)tb.onclick=()=>t.hidden=false;document.querySelectorAll('[data-close-tutorial]').forEach(x=>x.onclick=()=>t.hidden=true)}
function vlibras(){if(document.querySelector('[vw]'))return;const box=document.createElement('div');box.setAttribute('vw','');box.className='enabled';box.innerHTML='<div vw-access-button class="active"></div><div vw-plugin-wrapper><div class="vw-plugin-top-wrapper"></div></div>';document.body.append(box);const script=document.createElement('script');script.src='https://vlibras.gov.br/app/vlibras-plugin.js';script.onload=()=>new window.VLibras.Widget('https://vlibras.gov.br/app');document.body.append(script)}
document.addEventListener('DOMContentLoaded',()=>{applyTheme();vlibras();initAuth();initProfile();initAccess();if(location.pathname.endsWith('cliente.html'))initClient();if(location.pathname.endsWith('relatorios.html'))initReports();if(location.pathname.endsWith('admin.html'))initAdmin();if(location.pathname.endsWith('clientes.html'))initClients()});
